version: '3.8'

services:
  word-gen-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./DashboardWordGen/Dashboard:/app/DashboardWordGen/Dashboard:ro
      - ./DashboardWordGen/requirements.txt:/app/DashboardWordGen/requirements.txt:ro
    restart: always
    environment:
      - STREAMLIT_LOGGER_LEVEL=info
    # Configurações adicionais para produção
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
